application: ezselector2
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on
- deferred: on
- appstats: on

# inbound_services:
# - warmup


libraries:
- name: jinja2
  version: "latest"
- name: lxml
  version: "latest"


handlers:
- url: /.*
  script: urls.app

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?.*\.(rb|scss|DS_Store|zip|log)$
- ^htmlcov/.*
- ^google/.*
- ^google_appengine/.*


